# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196ff54026820ac4802ee8d8cc38723a99b77c7fe45ed0a70a11b73aa340581fb20e7e705f2b0f77599886e031cfc34e81ab4d13391f90a9366f64f49aa920d9

test:
  secret_key_base: 5c0c8379b44c2cf3af7eee0ef5bddba19be5c21108fcd53c5f6c970959d1532caf1514f7ef468ee8454ef270144c9d9b9db7abb3376647ba1267ec0a45ecd210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
